export const SIGNIN_USER_REQUEST = "SIGNIN_USER_REQUEST";
export const SIGNIN_USER_FAILUR = "SIGNIN_USER_FAILUR";
export const SIGNIN_USER_SUCCESS = "SIGNIN_USER_SUCCESS";

export const SIGNUP_USER_REQUEST = "SIGNUP_USER_REQUEST";
export const SIGNUP_USER_FAILUR = "SIGNUP_USER_FAILUR";
export const SIGNUP_USER_SUCCESS = "SIGNUP_USER_SUCCESS";

